package Project4.service;

// Generated Nov 21, 2015 2:35:13 PM by Hibernate Tools 3.4.0.CR1

/**
 * Administratortable generated by hbm2java
 */
public class Administratortable implements java.io.Serializable {

	private int id;
	private String name;
	private String password;

	public Administratortable() {
	}

	public Administratortable(int id, String name, String password) {
		this.id = id;
		this.name = name;
		this.password = password;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
