package Project4.service;

// Generated Nov 21, 2015 2:35:13 PM by Hibernate Tools 3.4.0.CR1

/**
 * Coursetable generated by hbm2java
 */
public class Coursetable implements java.io.Serializable {

	private String courseCode;
	private String name;
	private int taWeighting;
	private int enrollmentLimit;
	private String prereq;

	public Coursetable() {
	}

	public Coursetable(String courseCode, String name, int taWeighting,
			int enrollmentLimit) {
		this.courseCode = courseCode;
		this.name = name;
		this.taWeighting = taWeighting;
		this.enrollmentLimit = enrollmentLimit;
	}

	public Coursetable(String courseCode, String name, int taWeighting,
			int enrollmentLimit, String prereq) {
		this.courseCode = courseCode;
		this.name = name;
		this.taWeighting = taWeighting;
		this.enrollmentLimit = enrollmentLimit;
		this.prereq = prereq;
	}

	public String getCourseCode() {
		return this.courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getTaWeighting() {
		return this.taWeighting;
	}

	public void setTaWeighting(int taWeighting) {
		this.taWeighting = taWeighting;
	}

	public int getEnrollmentLimit() {
		return this.enrollmentLimit;
	}

	public void setEnrollmentLimit(int enrollmentLimit) {
		this.enrollmentLimit = enrollmentLimit;
	}

	public String getPrereq() {
		return this.prereq;
	}

	public void setPrereq(String prereq) {
		this.prereq = prereq;
	}

}
