package Project4.service;

// Generated Nov 21, 2015 2:35:13 PM by Hibernate Tools 3.4.0.CR1

/**
 * Studenttable generated by hbm2java
 */
public class Studenttable implements java.io.Serializable {

	private int id;
	private String name;
	private String password;
	private boolean ta;

	public Studenttable() {
	}

	public Studenttable(int id, String name, String password, boolean ta) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.ta = ta;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isTa() {
		return this.ta;
	}

	public void setTa(boolean ta) {
		this.ta = ta;
	}

}
