package Project4.service;

// Generated Nov 21, 2015 2:35:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Studentpreferencestable generated by hbm2java
 */
public class Studentpreferencestable implements java.io.Serializable {

	private int preferenceId;
	private Date date;
	private int studentId;
	private String courses;

	public Studentpreferencestable() {
	}

	public Studentpreferencestable(int preferenceId, Date date, int studentId,
			String courses) {
		this.preferenceId = preferenceId;
		this.date = date;
		this.studentId = studentId;
		this.courses = courses;
	}

	public int getPreferenceId() {
		return this.preferenceId;
	}

	public void setPreferenceId(int preferenceId) {
		this.preferenceId = preferenceId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public String getCourses() {
		return this.courses;
	}

	public void setCourses(String courses) {
		this.courses = courses;
	}

}
