package Project4.service;

// Generated Nov 21, 2015 2:35:13 PM by Hibernate Tools 3.4.0.CR1

/**
 * Sysinfo generated by hbm2java
 */
public class Sysinfo implements java.io.Serializable {

	private SysinfoId id;

	public Sysinfo() {
	}

	public Sysinfo(SysinfoId id) {
		this.id = id;
	}

	public SysinfoId getId() {
		return this.id;
	}

	public void setId(SysinfoId id) {
		this.id = id;
	}

}
