package edu.gatech.sad.project4.entities;

// Generated Nov 23, 2015 11:41:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Coursetable generated by hbm2java
 */
public class Coursetable implements java.io.Serializable {

	private String courseCode;
	private String name;
	private int taWeighting;
	private int enrollmentLimit;
	private String prereq;
	private boolean offered;
	private Integer professorId;

	public Coursetable() {
	}

	public Coursetable(String courseCode, String name, int taWeighting,
			int enrollmentLimit, boolean offered) {
		this.courseCode = courseCode;
		this.name = name;
		this.taWeighting = taWeighting;
		this.enrollmentLimit = enrollmentLimit;
		this.offered = offered;
	}

	public Coursetable(String courseCode, String name, int taWeighting,
			int enrollmentLimit, String prereq, boolean offered,
			Integer professorId) {
		this.courseCode = courseCode;
		this.name = name;
		this.taWeighting = taWeighting;
		this.enrollmentLimit = enrollmentLimit;
		this.prereq = prereq;
		this.offered = offered;
		this.professorId = professorId;
	}

	public String getCourseCode() {
		return this.courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getTaWeighting() {
		return this.taWeighting;
	}

	public void setTaWeighting(int taWeighting) {
		this.taWeighting = taWeighting;
	}

	public int getEnrollmentLimit() {
		return this.enrollmentLimit;
	}

	public void setEnrollmentLimit(int enrollmentLimit) {
		this.enrollmentLimit = enrollmentLimit;
	}

	public String getPrereq() {
		return this.prereq;
	}

	public void setPrereq(String prereq) {
		this.prereq = prereq;
	}

	public boolean isOffered() {
		return this.offered;
	}

	public void setOffered(boolean offered) {
		this.offered = offered;
	}

	public Integer getProfessorId() {
		return this.professorId;
	}

	public void setProfessorId(Integer professorId) {
		this.professorId = professorId;
	}

	@Override
	public String toString() {
		return "Coursetable [courseCode=" + courseCode + ", name=" + name
				+ ", taWeighting=" + taWeighting + ", enrollmentLimit="
				+ enrollmentLimit + ", prereq=" + prereq + ", offered="
				+ offered + ", professorId=" + professorId + "]";
	}

}
