package edu.gatech.sad.project4.entities;

// Generated Nov 21, 2015 2:37:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * Courseava generated by hbm2java
 */
public class Courseava implements java.io.Serializable {

	private String courseCode;
	private String semestersAvailable;

	public Courseava() {
	}

	public Courseava(String courseCode, String semestersAvailable) {
		this.courseCode = courseCode;
		this.semestersAvailable = semestersAvailable;
	}

	public String getCourseCode() {
		return this.courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

	public String getSemestersAvailable() {
		return this.semestersAvailable;
	}

	public void setSemestersAvailable(String semestersAvailable) {
		this.semestersAvailable = semestersAvailable;
	}

}
