package edu.gatech.sad.project4.entities;

// Generated Nov 25, 2015 3:17:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * Professorcourseassignmenttable generated by hbm2java
 */
public class Professorcourseassignmenttable implements java.io.Serializable {

	private ProfessorcourseassignmenttableId id;
	private String courseCode;

	public Professorcourseassignmenttable() {
	}

	public Professorcourseassignmenttable(ProfessorcourseassignmenttableId id) {
		this.id = id;
	}

	public Professorcourseassignmenttable(ProfessorcourseassignmenttableId id,
			String courseCode) {
		this.id = id;
		this.courseCode = courseCode;
	}

	public ProfessorcourseassignmenttableId getId() {
		return this.id;
	}

	public void setId(ProfessorcourseassignmenttableId id) {
		this.id = id;
	}

	public String getCourseCode() {
		return this.courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

}
