package edu.gatech.sad.project4.entities;

// Generated Nov 25, 2015 3:17:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * Professorstable generated by hbm2java
 */
public class Professorstable implements java.io.Serializable {

	private int professorId;
	private String name;
	private String courses;

	public Professorstable() {
	}

	public Professorstable(int professorId, String name) {
		this.professorId = professorId;
		this.name = name;
	}

	public Professorstable(int professorId, String name, String courses) {
		this.professorId = professorId;
		this.name = name;
		this.courses = courses;
	}

	public int getProfessorId() {
		return this.professorId;
	}

	public void setProfessorId(int professorId) {
		this.professorId = professorId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCourses() {
		return this.courses;
	}

	public void setCourses(String courses) {
		this.courses = courses;
	}

	@Override
	public String toString() {
		return "Professorstable [professorId=" + professorId + ", name=" + name
				+ ", courses=" + courses + "]";
	}

}
