package edu.gatech.sad.project4.entities;

// Generated Nov 23, 2015 11:41:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Studenttable generated by hbm2java
 */
public class Studenttable implements java.io.Serializable {

	private int id;
	private String name;
	private String password;
	private boolean ta;
	private int creditHoursCompleted;
	private String takenCourses;

	public Studenttable() {
	}

	public Studenttable(int id, String name, String password, boolean ta,
			int creditHoursCompleted) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.ta = ta;
		this.creditHoursCompleted = creditHoursCompleted;
	}

	public Studenttable(int id, String name, String password, boolean ta,
			int creditHoursCompleted, String takenCourses) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.ta = ta;
		this.creditHoursCompleted = creditHoursCompleted;
		this.takenCourses = takenCourses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isTa() {
		return this.ta;
	}

	public void setTa(boolean ta) {
		this.ta = ta;
	}

	public int getCreditHoursCompleted() {
		return this.creditHoursCompleted;
	}

	public void setCreditHoursCompleted(int creditHoursCompleted) {
		this.creditHoursCompleted = creditHoursCompleted;
	}

	public String getTakenCourses() {
		return this.takenCourses;
	}

	public void setTakenCourses(String takenCourses) {
		this.takenCourses = takenCourses;
	}

}
