package edu.gatech.sad.project4.entities;

// Generated Nov 21, 2015 11:15:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * SysinfoId generated by hbm2java
 */
public class SysinfoId implements java.io.Serializable {

	private int defaultTaWeighting;
	private int maxCoursesPerSemester;

	public SysinfoId() {
	}

	public SysinfoId(int defaultTaWeighting, int maxCoursesPerSemester) {
		this.defaultTaWeighting = defaultTaWeighting;
		this.maxCoursesPerSemester = maxCoursesPerSemester;
	}

	public int getDefaultTaWeighting() {
		return this.defaultTaWeighting;
	}

	public void setDefaultTaWeighting(int defaultTaWeighting) {
		this.defaultTaWeighting = defaultTaWeighting;
	}

	public int getMaxCoursesPerSemester() {
		return this.maxCoursesPerSemester;
	}

	public void setMaxCoursesPerSemester(int maxCoursesPerSemester) {
		this.maxCoursesPerSemester = maxCoursesPerSemester;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SysinfoId))
			return false;
		SysinfoId castOther = (SysinfoId) other;

		return (this.getDefaultTaWeighting() == castOther
				.getDefaultTaWeighting())
				&& (this.getMaxCoursesPerSemester() == castOther
						.getMaxCoursesPerSemester());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDefaultTaWeighting();
		result = 37 * result + this.getMaxCoursesPerSemester();
		return result;
	}

}
