package edu.gatech.sad.project4.entities;

// Generated Nov 25, 2015 3:17:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * Tacourseassignmenttable generated by hbm2java
 */
public class Tacourseassignmenttable implements java.io.Serializable {

	private TacourseassignmenttableId id;
	private String courseCode;

	public Tacourseassignmenttable() {
	}

	public Tacourseassignmenttable(TacourseassignmenttableId id) {
		this.id = id;
	}

	public Tacourseassignmenttable(TacourseassignmenttableId id,
			String courseCode) {
		this.id = id;
		this.courseCode = courseCode;
	}

	public TacourseassignmenttableId getId() {
		return this.id;
	}

	public void setId(TacourseassignmenttableId id) {
		this.id = id;
	}

	public String getCourseCode() {
		return this.courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

}
