package edu.gatech.sad.project4.entities;

// Generated Nov 25, 2015 3:17:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * TacourseassignmenttableId generated by hbm2java
 */
public class TacourseassignmenttableId implements java.io.Serializable {

	private int processingStatusId;
	private int studentId;

	public TacourseassignmenttableId() {
	}

	public TacourseassignmenttableId(int processingStatusId, int studentId) {
		this.processingStatusId = processingStatusId;
		this.studentId = studentId;
	}

	public int getProcessingStatusId() {
		return this.processingStatusId;
	}

	public void setProcessingStatusId(int processingStatusId) {
		this.processingStatusId = processingStatusId;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TacourseassignmenttableId))
			return false;
		TacourseassignmenttableId castOther = (TacourseassignmenttableId) other;

		return (this.getProcessingStatusId() == castOther
				.getProcessingStatusId())
				&& (this.getStudentId() == castOther.getStudentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProcessingStatusId();
		result = 37 * result + this.getStudentId();
		return result;
	}

}
